[project]
name = "ml-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.4.0",
    "my-module>=1.6.2",
    "numpy>=2.2.5",
]
